# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Tara Radvand's Homepage"
title_separator          : "-"
name                     : &name "Tara Radvand"
description              : &description "Ph.D. Candidate in Technology and Operations at Ross School of Business, University of Michigan, specializing in transportation, operations research, and supply chain management."
url                      : https://academicpages.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png"  # Replace with actual image filename if available
  name             : "Tara Radvand"
  pronouns         : "she/her"  # Assumed based on common usage; adjust if incorrect
  bio              : "Ph.D. Candidate in Technology and Operations at Ross School of Business"
  location         : "Ann Arbor, MI, USA"
  employer         : "Ross School of Business, University of Michigan"
  uri              :  # Add personal website URL if applicable
  email            : "tararad@umich.edu"

  # Academic websites
  arxiv            :  # Add if you have an arXiv profile
  googlescholar    : "https://scholar.google.com/citations?user=yourID"  # Replace with your actual Google Scholar URL
  impactstory      :  # Add if applicable
  semantic         :  # Add if applicable
  pubmed           :  # Add if applicable
  researchgate     : "https://www.researchgate.net/profile/Tara-Radvand"  # Replace with your ResearchGate URL if available
  scopus           :  # Add if applicable

  # Repositories and software development
  bitbucket        :  # Add if applicable
  codepen          :  # Add if applicable
  dribbble         :  # Add if applicable
  kaggle           :  # Add if applicable
  stackoverflow    :  # Add if applicable

  # Social media
  bluesky          :  # Add if applicable
  facebook         :  # Add if applicable
  flickr           :  # Add if applicable
  foursquare       :  # Add if applicable
  goodreads        :  # Add if applicable
  google_plus      :  # Add if applicable
  keybase          :  # Add if applicable
  instagram        :  # Add if applicable
  lastfm           :  # Add if applicable
  linkedin         : "tara-radvand"  # Replace with your LinkedIn username
  mastodon         :  # Add if applicable
  medium           :  # Add if applicable
  pinterest        :  # Add if applicable
  soundcloud       :  # Add if applicable
  steam            :  # Add if applicable
  telegram         :  # Add if applicable
  tumblr           :  # Add if applicable
  vine             :  # Add if applicable
  weibo            :  # Add if applicable
  wikipedia        :  # Add if applicable
  xing             :  # Add if applicable
  youtube          :  # Add if applicable
  zhihu            :  # Add if applicable

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings (unchanged unless specified)
teaser                   :  # Add a teaser image filename if desired
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :  # Set to "disqus" or another provider if you want comments
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   : ""

# SEO Related (unchanged unless you provide specific verification codes)
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "TaraRadvand"  # Replace with your Twitter/X handle
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Add an image filename for social sharing if desired
social:
  type                   : "Person"
  name                   : "Tara Radvand"
  links:
    - "https://www.linkedin.com/in/tara-radvand"  # Replace with your LinkedIn URL
    - "https://twitter.com/TaraRadvand"  # Replace with your Twitter URL
    - "https://github.com/tararadvand"  # Replace with your GitHub URL if applicable
    - "https://www.researchgate.net/profile/Tara-Radvand"  # Replace with your ResearchGate URL if applicable

# Analytics (unchanged unless you provide a tracking ID)
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Remaining sections (unchanged as they are structural or require additional content files)
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections (unchanged, but you can add content to these later)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults (unchanged)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS (unchanged)
sass:
  sass_dir: _sass
  style: compressed

# Outputting (unchanged)
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins (unchanged)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Whitelist (unchanged)
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives (unchanged)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression (unchanged)
compress_html:
  clippings: all
  ignore:
    envs: development
